"""Deterministic in-process worker used to exercise the broker without hardware.

This exists so the queue, the lease, the event stream, the tree and the
completion contract can be developed and tested without a GPU machine on the
other end. It is gated by ``Settings.recursive_fake_worker_enabled``, which
additionally refuses to switch on inside a Replit deployment.

Everything it produces is labelled as a simulation -- ``is_simulation`` on the
result, ``simulation: true`` on the completion event, and an opening line in
the response text itself. A reader must never be able to mistake this output
for analysis a real model performed.
"""
from __future__ import annotations

import logging
import uuid
from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from ..config import Settings, get_settings
from ..models import RecursiveWorker
from ..schemas import (
    RecursiveCompletionIn,
    RecursiveEventBatchIn,
    RecursiveResultNodeIn,
    RecursiveRuntimeIn,
    RecursiveUsageIn,
    RecursiveWorkerEventIn,
)
from . import broker, worker_events

logger = logging.getLogger("vls.recursive.fake")

FAKE_WORKER_NAME = "Simulated recursive worker (development)"
FAKE_MODEL_KEY = "simulated/recursive-coordinator"
SIMULATION_NOTICE = (
    "[SIMULATED RECURSIVE OUTPUT — no external model was called. This text is "
    "generated by the development simulator and is not research output.]"
)


def _catalog() -> list[dict]:
    return [
        {
            "model_key": FAKE_MODEL_KEY,
            "display_name": "Simulated coordinator",
            "provider_kind": "simulated",
            "context_window": 128_000,
            "supports_recursive_agents": True,
            "supports_tools": True,
            # Priced at zero *and* declared complete: a simulation genuinely
            # costs nothing, and saying so is different from not knowing.
            "pricing": {
                "input_usd_per_1m": 0.0,
                "cached_input_usd_per_1m": 0.0,
                "output_usd_per_1m": 0.0,
            },
        }
    ]


def _capabilities() -> dict:
    return {
        "sandbox_mode": "process",
        "supports_recursive_agents": True,
        "supports_python": True,
        "supports_evidence_search": True,
        "allow_web": False,
        "max_children": 8,
        "max_depth": 2,
        "profiles": ["research_read_only"],
    }


async def ensure_fake_worker(db: AsyncSession, workspace_id: uuid.UUID) -> RecursiveWorker:
    """Idempotently provide a simulated worker for a workspace, kept fresh.

    Its credential hash is a sentinel that cannot be produced by the real
    minting path, so the simulated worker can never be authenticated against
    over HTTP -- it is only reachable in-process.
    """
    # Oldest-first with a limit rather than scalar_one_or_none(): display names
    # are not unique per workspace, and a simulator that crashes because a
    # duplicate exists would be worse than one that consistently picks the same
    # row.
    worker = (
        await db.execute(
            select(RecursiveWorker)
            .where(
                RecursiveWorker.workspace_id == workspace_id,
                RecursiveWorker.display_name == FAKE_WORKER_NAME,
            )
            .order_by(RecursiveWorker.created_at.asc())
            .limit(1)
        )
    ).scalars().first()
    now = datetime.now(UTC)
    if worker is None:
        worker = RecursiveWorker(
            workspace_id=workspace_id,
            display_name=FAKE_WORKER_NAME,
            status="online",
            enabled=True,
            token_prefix=f"sim{uuid.uuid4().hex[:9]}",
            token_hash="simulated:not-a-credential",
            adapter_version="simulated",
            prime_agent_version="simulated",
            sandbox_mode="process",
            capabilities=_capabilities(),
            model_catalog=_catalog(),
            last_seen_at=now,
        )
        db.add(worker)
    else:
        worker.status = "online"
        worker.enabled = True
        worker.revoked_at = None
        worker.capabilities = _capabilities()
        worker.model_catalog = _catalog()
        worker.last_seen_at = now
    await db.commit()
    return worker


def _build_result(job, settings: Settings) -> RecursiveCompletionIn:
    request = job.request_json or {}
    participant = request.get("participant", {})
    evidence = request.get("evidence", []) or []
    child_count = min(2, job.max_children)

    lines = [
        SIMULATION_NOTICE,
        "",
        f"As {participant.get('display_name', 'the participant')}, I decomposed this turn "
        f"into {child_count} focused sub-questions and reconciled their findings.",
        "",
    ]
    if evidence:
        for item in evidence[:3]:
            lines.append(
                f"- Evidence {item.get('evidence_key')} ({item.get('title')}) was reviewed for "
                "relevance to the agenda."
            )
    else:
        lines.append(
            "- No evidence was attached to this meeting, so nothing could be examined."
        )
    lines += [
        "",
        "Limitations: this response is simulator output and contains no analysis of the "
        "underlying sources.",
    ]

    nodes = [
        RecursiveResultNodeIn(
            external_node_id="root",
            parent_external_node_id=None,
            display_name="Coordinator",
            status="completed",
            model_key=job.model_key,
            task_summary="Plan the turn and reconcile child findings.",
            result_summary="Produced the participant's final response.",
            usage=RecursiveUsageIn(model_call_count=1, input_tokens=400, output_tokens=200),
        )
    ]
    for index in range(child_count):
        nodes.append(
            RecursiveResultNodeIn(
                external_node_id=f"child-{index + 1}",
                parent_external_node_id="root",
                display_name=f"Sub-agent {index + 1}",
                status="completed",
                model_key=job.child_model_key or job.model_key,
                task_summary=f"Investigate sub-question {index + 1}.",
                result_summary="Reported a simulated finding.",
                cited_evidence_keys=[
                    str(e.get("evidence_key")) for e in evidence[:1] if e.get("evidence_key")
                ],
                tool_labels=["Frozen evidence search"],
                usage=RecursiveUsageIn(
                    model_call_count=1, input_tokens=200, output_tokens=120
                ),
            )
        )

    total_calls = min(len(nodes), job.max_agent_turns)
    return RecursiveCompletionIn(
        request_sha256=job.request_sha256,
        final_text="\n".join(lines),
        citations=[],
        limitations=["Simulated output; no external model was consulted."],
        usage=RecursiveUsageIn(
            model_call_count=total_calls,
            input_tokens=min(600 * total_calls, job.max_tokens // 2),
            output_tokens=min(320 * total_calls, job.max_tokens // 2),
            cost_usd=0.0,
            pricing_complete=True,
        ),
        runtime=RecursiveRuntimeIn(
            adapter_version="simulated",
            prime_agent_version="simulated",
            model_key=job.model_key,
            child_model_key=job.child_model_key,
            elapsed_ms=1200,
            is_simulation=True,
        ),
        nodes=nodes,
    )


async def run_once(db: AsyncSession, workspace_id: uuid.UUID) -> uuid.UUID | None:
    """Lease at most one job for this workspace and finish it. Returns its id.

    Drives the same broker entry points a real worker uses over HTTP, so the
    simulator exercises the real state machine rather than a parallel one.
    """
    settings = get_settings()
    if not settings.recursive_fake_worker_enabled:
        return None

    worker = await ensure_fake_worker(db, workspace_id)
    job = await broker.lease_next_job(
        db,
        worker,
        supported_profiles=["research_read_only"],
        model_keys=[m["model_key"] for m in _catalog()],
        settings=settings,
    )
    if job is None:
        return None

    now = datetime.now(UTC)
    events = [
        RecursiveWorkerEventIn(
            external_event_id=f"{job.id}-started",
            worker_sequence=1,
            occurred_at=now,
            type="recursive.job.started",
        ),
        RecursiveWorkerEventIn(
            external_event_id=f"{job.id}-root",
            worker_sequence=2,
            occurred_at=now,
            type="recursive.agent.started",
            node={"external_node_id": "root", "display_name": "Coordinator"},
            payload={"task_summary": "Plan the turn.", "model_key": job.model_key},
        ),
    ]
    batch = RecursiveEventBatchIn(events=events)
    await worker_events.ingest_batch(
        db, job, batch.events, batch_max=settings.recursive_job_event_batch_max
    )
    if job.status == "leased":
        job.status = "running"
    await broker.renew_job_lease(db, job, worker, settings)
    await db.commit()

    result = _build_result(job, settings)
    try:
        await broker.complete_job(db, job.id, worker, result)
    except broker.JobRejected as exc:
        logger.warning("Simulated worker result refused: %s", exc.safe_message)
        return None
    logger.info("Simulated worker completed recursive job %s", job.id)
    return job.id


async def tick(sessionmaker: async_sessionmaker[AsyncSession]) -> int:
    """One pass over every workspace with parked recursive work."""
    settings = get_settings()
    if not settings.recursive_fake_worker_enabled:
        return 0
    handled = 0
    async with sessionmaker() as db:
        from ..models import RecursiveAgentJob, Run

        workspace_ids = (
            await db.execute(
                select(RecursiveAgentJob.workspace_id)
                .join(Run, Run.id == RecursiveAgentJob.run_id)
                .where(
                    RecursiveAgentJob.status == "queued",
                    Run.status == "waiting_external",
                )
                .distinct()
                .limit(10)
            )
        ).scalars().all()
        for workspace_id in workspace_ids:
            if await run_once(db, workspace_id) is not None:
                handled += 1
    return handled
