"""Model provider protocol and the deterministic Demo Provider.

The Demo Provider replays the scripted scenario in
specs/demo_provider_scenario.json when the run matches, and otherwise emits a
clearly labeled deterministic simulated response derived from a SHA-256 hash
of run ID, call index, and agent title. It never contacts a network service
and costs nothing.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any, Protocol

from .config import SPECS_DIR


@dataclass
class CompletionRequest:
    model: str
    system_prompt: str
    messages: list[dict[str, str]]
    temperature: float
    run_id: str
    call_index: int
    agent_title: str
    role_type: str
    round_number: int
    is_final: bool
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class ToolCallRequest:
    tool_slug: str
    arguments: dict[str, Any]
    result: dict[str, Any]
    label: str


@dataclass
class CompletionResult:
    content: str
    finish_reason: str
    provider_request_id: str | None
    model: str
    input_tokens: int
    cached_input_tokens: int
    output_tokens: int
    cost_usd: float
    latency_ms: int
    is_simulation: bool
    tool_calls: list[ToolCallRequest] = field(default_factory=list)
    structured_summary: dict[str, Any] | None = None


class ModelProvider(Protocol):
    provider_type: str

    async def complete(self, request: CompletionRequest) -> CompletionResult: ...


class DemoProvider:
    provider_type = "demo"

    def __init__(self) -> None:
        spec = json.loads((SPECS_DIR / "demo_provider_scenario.json").read_text())
        self.provider_spec = spec["provider"]
        self.scenario = spec["scenario"]
        self.fallback = spec["fallback_behavior"]
        self.disclosure: str = self.provider_spec["required_disclosure"]
        usage = self.provider_spec["usage"]
        self.input_tokens_per_call = int(usage["input_tokens_per_call"])
        self.output_tokens_per_call = int(usage["output_tokens_per_call"])

    def matches_scenario(self, project_slug: str, meeting_type: str, rounds: int) -> bool:
        match = self.scenario["match"]
        return (
            match["project_slug"] == project_slug
            and match["meeting_type"] == meeting_type
            and int(match["rounds"]) == rounds
        )

    def scripted_call(self, call_index: int) -> dict[str, Any] | None:
        for call in self.scenario["scripted_calls"]:
            if int(call["call_index"]) == call_index:
                return call
        return None

    def tool_events_after(self, call_index: int) -> list[dict[str, Any]]:
        return [
            ev for ev in self.scenario.get("simulated_tool_events", [])
            if int(ev["after_call_index"]) == call_index
        ]

    def structured_summary(self) -> dict[str, Any]:
        return self.scenario["structured_summary"]

    def _fallback_content(self, request: CompletionRequest) -> str:
        digest = hashlib.sha256(
            f"{request.run_id}:{request.call_index}:{request.agent_title}".encode()
        ).hexdigest()[:12]
        stage = "final synthesis" if request.is_final else f"discussion round {request.round_number}"
        return (
            f"[Simulation] {request.agent_title} — {stage}. "
            f"This is deterministic placeholder discussion (fingerprint {digest}) generated by the "
            "Demo Provider for interface testing. It is not substantive scientific analysis. "
            "Connect a real model provider and attach reviewed evidence before using this "
            "meeting for research decisions. Cost: $0."
        )

    async def complete(
        self, request: CompletionRequest, scripted: bool = False
    ) -> CompletionResult:
        if scripted:
            call = self.scripted_call(request.call_index)
        else:
            call = None
        content = call["content"] if call else self._fallback_content(request)
        digest = hashlib.sha256(content.encode()).hexdigest()[:16]
        return CompletionResult(
            content=content,
            finish_reason="stop",
            provider_request_id=f"demo-{request.run_id[:8]}-{request.call_index}-{digest[:6]}",
            model=self.provider_spec["model_key"],
            input_tokens=self.input_tokens_per_call,
            cached_input_tokens=0,
            output_tokens=self.output_tokens_per_call,
            cost_usd=0.0,
            latency_ms=int(self.scenario["simulated_latency_ms"]["first_token"]),
            is_simulation=True,
        )


_demo_provider: DemoProvider | None = None


def get_demo_provider() -> DemoProvider:
    global _demo_provider
    if _demo_provider is None:
        _demo_provider = DemoProvider()
    return _demo_provider


def get_provider(provider_type: str) -> DemoProvider:
    """Provider registry. v1 foundation ships the Demo Provider; OpenAI and
    OpenAI-compatible adapters plug in behind the same protocol."""
    if provider_type == "demo":
        return get_demo_provider()
    raise LookupError(f"Provider type '{provider_type}' is not configured in this environment")
